### ISSUE TITLE
New Y-Rod Holder teds to flex

### ISSUE THREAD

**Issue by themaxx2k** [AxMod3DPrint/FB2020#10]
The new designed Rod holders are a very good solution, however after 3 days the unfixed side tends to bend downwards. It would be a nice variant if you could redesign the rod holders to have a mounting hole on both sides. To mount them it would be required to remove the inner corner brackets, which can be replaced by two L-Brackets, one on top, the other on the front / back. so the frame will stay rigid and we free up space for the second mounting point (outer side).
Thank you very much

**Comment by themaxx2k** [comment]
redesigned it by myself, based on AxMods Design: http://www.thingiverse.com/thing:2034817

**Comment by ViperWorx** [comment]
Hi there,

I had tried this in design iteration. However, you lose about 10mm or so on X by using them. In order to get the full 200 the X Extrusion length would need to be increased. I'm loathed to make such a major change to the structure at this point having 3 FB2020s running at the moment. I hadn't actually noticed the bracket flexing, so thankyou for pointing that out. I have an idea in mind to fix it, though without actually losing usable space. I'll be working on this later.

**Comment by themaxx2k** [comment]
you are right, when using the normal corner brackets, so i will replace them (currently printing them :-) and will report.

**Comment by ViperWorx** [comment]
The Holders have been updated. Not printed as yet, but should work without issue.

**Comment by themaxx2k** [comment]
mine are installed. working fine.

**Comment by themaxx2k** [comment]
Your solution is also really cool. So this issue does not exist any more :-)
