### ISSUE TITLE
Auto level probe

### ISSUE THREAD

**Issue by ttl64** [AxMod3DPrint/FB2020#6]
Add support for induction sensing probe for auto bed leveling

**Comment by ViperWorx** [comment]
@I've looked at this as an option but have dismissed it several times due to the following reasons: 
A) The Carriage/Hotend space is _very_ compact and it would be very difficult to fit a sensor in without it fouling on something whether it be a barrel type, or a SN-04. 

B) The bed is solid and with the 3 point levelling, simple to level. There is actually a GCode file in the GCode folder you can drop on to an SD Card which adds guidance for the levelling. I

 have not levelled the beds on both the Plus and Standard in about 50-60 hours of printing, therefore, I don't feel it is necessary to add.
